---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.2
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
install: bundle install --jobs=3 --retry=3
env:
  - DISABLE_SIMPLECOV=true
script: ./.travis.sh

